packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.6.0
  prettier: ^3.3.2
  typescript: ^5.5.3
  zod: ^3.23.8
  tailwindcss: ^3.4.7
  "@types/node": ^20.14.14
  "dotenv-cli": ^7.4.2
  "@t3-oss/env-core": ^0.11.0
  "@t3-oss/env-nextjs": ^0.11.0
  "jiti": ^1.21.6

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0
  react19:
    react: ^19.0.0-rc-6230622a1a-20240610
    react-dom: ^19.0.0-rc-6230622a1a-20240610
    "@types/react": npm:types-react-dom@19.0.0-rc.0
    "@types/react-dom": npm:types-react-dom@19.0.0-rc.0
