packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.51.23
  "@trpc/client": ^11.0.0-rc.477
  "@trpc/react-query": ^11.0.0-rc.477
  "@trpc/server": ^11.0.0-rc.477
  eslint: ^9.9.0
  prettier: ^3.3.3
  tailwindcss: ^3.4.10
  typescript: ^5.5.4
  zod: ^3.23.8
  "@types/node": ^20.14.15
  "dotenv-cli": ^7.4.2
  "@t3-oss/env-core": ^0.11.0
  "@t3-oss/env-nextjs": ^0.11.0
  "jiti": ^1.21.6

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0
  react19:
    react: 19.0.0-rc-06d0b89e-20240801
    react-dom: 19.0.0-rc-06d0b89e-20240801
    "@types/react": npm:types-react@19.0.0-rc.0
    "@types/react-dom": npm:types-react-dom@19.0.0-rc.0
